# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/working/Basys-3-Master.xdc

# Block Designs: bd/i2c_cpu/i2c_cpu.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==i2c_cpu || ORIG_REF_NAME==i2c_cpu} -quiet] -quiet

# IP: bd/i2c_cpu/ip/i2c_cpu_axi_uartlite_0_0/i2c_cpu_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==i2c_cpu_axi_uartlite_0_0 || ORIG_REF_NAME==i2c_cpu_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/i2c_cpu/ip/i2c_cpu_gpio_0_0/i2c_cpu_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==i2c_cpu_gpio_0_0 || ORIG_REF_NAME==i2c_cpu_gpio_0_0} -quiet] -quiet

# IP: bd/i2c_cpu/ip/i2c_cpu_gpio_1_0/i2c_cpu_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==i2c_cpu_gpio_1_0 || ORIG_REF_NAME==i2c_cpu_gpio_1_0} -quiet] -quiet

# IP: bd/i2c_cpu/ip/i2c_cpu_gpio_2_0/i2c_cpu_gpio_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==i2c_cpu_gpio_2_0 || ORIG_REF_NAME==i2c_cpu_gpio_2_0} -quiet] -quiet

# IP: bd/i2c_cpu/ip/i2c_cpu_i2c_master_0_0/i2c_cpu_i2c_master_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==i2c_cpu_i2c_master_0_0 || ORIG_REF_NAME==i2c_cpu_i2c_master_0_0} -quiet] -quiet

# IP: bd/i2c_cpu/ip/i2c_cpu_microblaze_0_2/i2c_cpu_microblaze_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==i2c_cpu_microblaze_0_2 || ORIG_REF_NAME==i2c_cpu_microblaze_0_2} -quiet] -quiet

# IP: bd/i2c_cpu/ip/i2c_cpu_dlmb_v10_1/i2c_cpu_dlmb_v10_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==i2c_cpu_dlmb_v10_1 || ORIG_REF_NAME==i2c_cpu_dlmb_v10_1} -quiet] -quiet

# IP: bd/i2c_cpu/ip/i2c_cpu_ilmb_v10_1/i2c_cpu_ilmb_v10_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==i2c_cpu_ilmb_v10_1 || ORIG_REF_NAME==i2c_cpu_ilmb_v10_1} -quiet] -quiet

# IP: bd/i2c_cpu/ip/i2c_cpu_dlmb_bram_if_cntlr_1/i2c_cpu_dlmb_bram_if_cntlr_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==i2c_cpu_dlmb_bram_if_cntlr_1 || ORIG_REF_NAME==i2c_cpu_dlmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/i2c_cpu/ip/i2c_cpu_ilmb_bram_if_cntlr_1/i2c_cpu_ilmb_bram_if_cntlr_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==i2c_cpu_ilmb_bram_if_cntlr_1 || ORIG_REF_NAME==i2c_cpu_ilmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/i2c_cpu/ip/i2c_cpu_lmb_bram_1/i2c_cpu_lmb_bram_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==i2c_cpu_lmb_bram_1 || ORIG_REF_NAME==i2c_cpu_lmb_bram_1} -quiet] -quiet

# IP: bd/i2c_cpu/ip/i2c_cpu_mdm_1_1/i2c_cpu_mdm_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==i2c_cpu_mdm_1_1 || ORIG_REF_NAME==i2c_cpu_mdm_1_1} -quiet] -quiet

# IP: bd/i2c_cpu/ip/i2c_cpu_clk_wiz_1_1/i2c_cpu_clk_wiz_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==i2c_cpu_clk_wiz_1_1 || ORIG_REF_NAME==i2c_cpu_clk_wiz_1_1} -quiet] -quiet

# IP: bd/i2c_cpu/ip/i2c_cpu_rst_clk_wiz_1_100M_1/i2c_cpu_rst_clk_wiz_1_100M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==i2c_cpu_rst_clk_wiz_1_100M_1 || ORIG_REF_NAME==i2c_cpu_rst_clk_wiz_1_100M_1} -quiet] -quiet

# IP: bd/i2c_cpu/ip/i2c_cpu_xbar_1/i2c_cpu_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==i2c_cpu_xbar_1 || ORIG_REF_NAME==i2c_cpu_xbar_1} -quiet] -quiet

# IP: bd/i2c_cpu/ip/i2c_cpu_microblaze_0_axi_periph_1/i2c_cpu_microblaze_0_axi_periph_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==i2c_cpu_microblaze_0_axi_periph_1 || ORIG_REF_NAME==i2c_cpu_microblaze_0_axi_periph_1} -quiet] -quiet

# XDC: d:/working/systemverilog/2025_11_14_I2C_IP_project/2025_11_14_I2C_IP_project.gen/sources_1/bd/i2c_cpu/ip/i2c_cpu_axi_uartlite_0_0/i2c_cpu_axi_uartlite_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==i2c_cpu_axi_uartlite_0_0 || ORIG_REF_NAME==i2c_cpu_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/working/systemverilog/2025_11_14_I2C_IP_project/2025_11_14_I2C_IP_project.gen/sources_1/bd/i2c_cpu/ip/i2c_cpu_axi_uartlite_0_0/i2c_cpu_axi_uartlite_0_0_ooc.xdc

# XDC: d:/working/systemverilog/2025_11_14_I2C_IP_project/2025_11_14_I2C_IP_project.gen/sources_1/bd/i2c_cpu/ip/i2c_cpu_axi_uartlite_0_0/i2c_cpu_axi_uartlite_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==i2c_cpu_axi_uartlite_0_0 || ORIG_REF_NAME==i2c_cpu_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/working/systemverilog/2025_11_14_I2C_IP_project/2025_11_14_I2C_IP_project.gen/sources_1/bd/i2c_cpu/ip/i2c_cpu_microblaze_0_2/i2c_cpu_microblaze_0_2.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==i2c_cpu_microblaze_0_2 || ORIG_REF_NAME==i2c_cpu_microblaze_0_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/working/systemverilog/2025_11_14_I2C_IP_project/2025_11_14_I2C_IP_project.gen/sources_1/bd/i2c_cpu/ip/i2c_cpu_microblaze_0_2/i2c_cpu_microblaze_0_2_ooc_debug.xdc

# XDC: d:/working/systemverilog/2025_11_14_I2C_IP_project/2025_11_14_I2C_IP_project.gen/sources_1/bd/i2c_cpu/ip/i2c_cpu_lmb_bram_1/i2c_cpu_lmb_bram_1_ooc.xdc

# XDC: d:/working/systemverilog/2025_11_14_I2C_IP_project/2025_11_14_I2C_IP_project.gen/sources_1/bd/i2c_cpu/ip/i2c_cpu_mdm_1_1/i2c_cpu_mdm_1_1.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==i2c_cpu_mdm_1_1 || ORIG_REF_NAME==i2c_cpu_mdm_1_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/working/systemverilog/2025_11_14_I2C_IP_project/2025_11_14_I2C_IP_project.gen/sources_1/bd/i2c_cpu/ip/i2c_cpu_mdm_1_1/i2c_cpu_mdm_1_1_ooc_trace.xdc

# XDC: d:/working/systemverilog/2025_11_14_I2C_IP_project/2025_11_14_I2C_IP_project.gen/sources_1/bd/i2c_cpu/ip/i2c_cpu_clk_wiz_1_1/i2c_cpu_clk_wiz_1_1_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==i2c_cpu_clk_wiz_1_1 || ORIG_REF_NAME==i2c_cpu_clk_wiz_1_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/working/systemverilog/2025_11_14_I2C_IP_project/2025_11_14_I2C_IP_project.gen/sources_1/bd/i2c_cpu/ip/i2c_cpu_clk_wiz_1_1/i2c_cpu_clk_wiz_1_1.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==i2c_cpu_clk_wiz_1_1 || ORIG_REF_NAME==i2c_cpu_clk_wiz_1_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/working/systemverilog/2025_11_14_I2C_IP_project/2025_11_14_I2C_IP_project.gen/sources_1/bd/i2c_cpu/ip/i2c_cpu_clk_wiz_1_1/i2c_cpu_clk_wiz_1_1_ooc.xdc

# XDC: d:/working/systemverilog/2025_11_14_I2C_IP_project/2025_11_14_I2C_IP_project.gen/sources_1/bd/i2c_cpu/ip/i2c_cpu_rst_clk_wiz_1_100M_1/i2c_cpu_rst_clk_wiz_1_100M_1_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==i2c_cpu_rst_clk_wiz_1_100M_1 || ORIG_REF_NAME==i2c_cpu_rst_clk_wiz_1_100M_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/working/systemverilog/2025_11_14_I2C_IP_project/2025_11_14_I2C_IP_project.gen/sources_1/bd/i2c_cpu/ip/i2c_cpu_rst_clk_wiz_1_100M_1/i2c_cpu_rst_clk_wiz_1_100M_1.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==i2c_cpu_rst_clk_wiz_1_100M_1 || ORIG_REF_NAME==i2c_cpu_rst_clk_wiz_1_100M_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/working/systemverilog/2025_11_14_I2C_IP_project/2025_11_14_I2C_IP_project.gen/sources_1/bd/i2c_cpu/i2c_cpu_ooc.xdc
